Contribution Guide
hanschehaiber/SignalMixer pull request #1
Opened 2023-11-10 22:55 UTC by NBS-LLC

* Branch name and commit message guidelines
* This prepares the project for automated changelogs and release notes

2023-11-18 01:54 UTC, hanschehaiber requested changes

2023-11-18 01:54 UTC, hanschehaiber commented on CONTRIBUTING.md
> +Branches must be prefixed with a category followed by a slash.
This looks good but wondering about branches that fit into multiple categories. 

It common to piggyback some chore (refactoring or code cleanup) on a new feature for example.

2023-11-18 20:44 UTC, NBS-LLC commented on CONTRIBUTING.md
> +Branches must be prefixed with a category followed by a slash.
Nah, stick with the main purpose of the branch being the prefix. So really its: `feature/some-cool-feature`. Then you'll do something like: `chore: cleaning up some old stuff` as a **commit message** on that branch. Try to group your changes by commit.

2023-11-18 21:53 UTC, NBS-LLC commented on CONTRIBUTING.md
> +Branches must be prefixed with a category followed by a slash.
I added some more details, let me know if that helps or adds noise.

We should also strive for concise documentation, less to maintain.

2023-11-19 01:06 UTC, hanschehaiber approved these changes

2023-11-19 01:06 UTC, merged